In [ ]:
import numpy as np

here i have installed numpy for working with arrays

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)      # element-wise addition
print(a * b)      # element-wise multiplication
print(a.dot(b))   # dot product
print(a.mean())   # average
print(a.sum())    # sum
print(a.max())    # max value

In [ ]:
#2D array(matrix)
b = np.array([[1,2,3] ,[4,5,6]])
print(b)

In [ ]:
# Built-in generators
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
rng = np.arange(0, 10, 2)      # start, stop, step
lin = np.linspace(0, 1, 5)     # 5 evenly spaced points between 0 and 1
rand = np.random.rand(3, 3)
#displaying above variables

In [ ]:
print(rand)
print(zeros)
print(rng)
print(lin)

In [ ]:
print(a.shape)   # dimensions
print(a.dtype)   # data type
print(a.ndim)    # number of dimensions

In [ ]:
print(b.shape)   # dimensions
print(b.dtype)   # data type
print(b.ndim)    # number of dimensions

In [ ]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m.ndim)
print(m.shape)

In [ ]:
import time

n = 5_000_000
a = np.arange(n)

# Loop version
start = time.time()
result = [x * 2 for x in a]
print("Loop:", time.time() - start)

# Vectorized version
start = time.time()
result = a * 2
print("Vectorized:", time.time() - start)

# New section

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url) # creating a dataframe

df.head()
df.tail(3)        # last 3 rows
df.shape          # (rows, columns)
df.columns        # column names
df.dtypes         # data type of each column
df.info()         # summary: types, non-null counts, memory
df.describe()     # statistical summary for numeric columns

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
url = "https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv"
df = pd.read_csv(url)

df.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

#1. Setup & Load Data
#2. Exploring the Data
#3. Selecting Columns
#4. Selecting Rows — .loc and .iloc
#5. Filtering Rows (Boolean Indexing)
#6. Handling Missing Data
#7. Sorting
#9. Grouping & Aggregation
#10. Value Counts & Unique Values
#11. Applying Functions
#12. Pivot Tables & Cross Tabulation
#13. Merging & Concatenating
#14. Exporting Data

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape              # (rows, columns)
df.columns             # list of column names
df.dtypes              # data type of each column
df.info()              # summary: nulls, types, memory
df.describe()          # stats for numeric columns
df.describe(include="object")   # stats for text/categorical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [ ]:
#df["Age"]                        # single column -> Series
df[["Name", "Age", "Fare"]]      # multiple columns -> DataFrame
#df.Age
df.Name
#df.Fare                          # dot notation (only works if no spaces in name)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
#4. Selecting Rows — .loc and .iloc
#df.loc[0]
# df.loc[0:5]
# df.iloc[0:5]
# df.loc[3,"Name"]

np.int64(3)

In [ ]:

df[df["Age"] > 30]
# here we are
df[df["Sex"] == "female"]
# df[(df["Pclass"] == 1) & (df["Survived"] == 1)]     # AND condition
# df[(df["Pclass"] == 1) | (df["Pclass"] == 2)]        # OR condition
df[df["Embarked"].isin(["S", "C"])]                    # isin()
df[~(df["Survived"] == 1)]                              # NOT condition

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# 6. Handling Missing Data
df.isnull().sum()                        # count nulls per column
df.isnull().mean() * 100  #% missing per column
# df["Age"].fillna(df["Age"].mean(), inplace=True)
# df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)
# df.dropna(subset=["Fare"], inplace=True)
# df.drop(columns=["Cabin"], inplace=True)              # drop a whole column

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [ ]:
df.head()
df.isnull().mean() * 100  #% missing per column

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [ ]:
#Sorting
df.sort_values("Fare")
df.sort_values("Fare", ascending = False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.000000,0,1,PC 17755,512.3292,C
258,259,1,1,"Ward, Miss. Anna",female,35.000000,0,0,PC 17755,512.3292,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.000000,0,0,PC 17755,512.3292,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,263.0000,S
438,439,0,1,"Fortune, Mr. Mark",male,64.000000,1,4,19950,263.0000,S
...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0000,S
815,816,0,1,"Fry, Mr. Richard",male,29.699118,0,0,112058,0.0000,S
466,467,0,2,"Campbell, Mr. William",male,29.699118,0,0,239853,0.0000,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,29.699118,0,0,239854,0.0000,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.000000,0,0,19972,0.0000,S